### PR TITLE
Increase buffer for performance increase...

### PR DESCRIPTION
**Pull request by isarrider**
according to https://github.com/nzbget/nzbget/issues/664
changed 4K -> 1M

### CODE REVIEW

**Comment by Batunga** [comment]
Hi! Did someone test how the larger buffer influences download speed on different systems/platforms?
On my Raspberry Pi 4 the download speed decreases quite a bit when I set the buffer to 1 MiB (from about 60 MiB/s to a bit below 40 MiB/s on a 500 Mbps fiber line). 16 KiB and 64 KiB were fine for me (as the default 4 KiB).
Maybe we need a config variable? Or at least OS dependent (?) values?

**Comment by isarrider** [comment]
interesting...
yap - maybe a config variable makes most sense...

**Comment by Batunga** [comment]
At least it seems to be possible to add a new config variable with limited efforts. I managed to get it working locally (including web UI, which seems to read the `nzbget.conf.template` file to build the list of available options for the web UI).
But I don't know how this template file is being built. Seems to be generated somehow when the software package is being built. But I didn't manage to build a nzbget installer/package when I tried it a few weeks ago.
Thus I currently don't know if it would be sufficient to just add the new option to the `nzbget.conf` file in the git repo's root directory or if more has to be done to get the new option into the template.

**Comment by isarrider** [comment]
maybe this will help - this commit should be similar (in terms of the config, not what it does):
https://github.com/nzbget/nzbget/commit/a2fab014d4856946e550d9086bd026eaa0f59989

**Comment by Batunga** [comment]
Thanks! Looks very similar to what I did. So seems that editing the `nzbget.conf` is enough.

**Comment by isarrider** [comment]
will you do a commit?

**Comment by Batunga** [comment]
Yes, but it might take a bit. Unfortunately I currently don't have much spare time. But I will try to create a PR in the next days.

**Comment by isarrider** [comment]
what system are you using btw?
I wanted to check again because:
https://github.com/nzbget/nzbget/issues/664#issuecomment-542668532

**Comment by Batunga** [comment]
I'm using a Raspberry Pi 4 (Linux/Debian 11 on AARCH64) for nzbget. It looks like only Windows will benefit from a larger buffer and maybe especially on low-powered(?) linux systems it could even hurt.
With the config variable you could try the best value for your system.
BTW: I created the new PR https://github.com/nzbget-ng/nzbget/pull/13 with my changes (new configuration).

**Comment by isarrider** [comment]
Ah, with a Pi4 that makes sense, it has only tiny $...
An option is indeed the best way...

**Comment by isarrider** [comment]
closing it here, as https://github.com/nzbget-ng/nzbget/pull/13 is superior...

**Pull request closed without merging**
